Error messages for login form
phpreboot/website pull request #153
Opened 2016-10-31 23:32 UTC by sahilsharma011

#152

2016-11-01 20:23 UTC, kapilsharma requested changes
Code from other issues also present in this PR. Thus it can be merged only once other PRs are merged and updated in this branch.

2016-11-01 20:23 UTC, kapilsharma commented on resources/views/auth/login.blade.php
> +                    @endif
Indentation wrong in two lines.

Only these changes are correct for issue #153. Other changes are coming due to merge on other issue. If we merge this PR, all other PR will be merged automatically. Thus, before we can merge this PE, we need to merge other PRs and update this branch from master.

2016-11-01 22:32 UTC, sahilsharma011 commented
@kapilsharma I've made the changes you asked for

2016-11-12 05:40 UTC, kapilsharma requested changes
This PR have lot of code which is not part of the issue. Probably happened due to incorrect branching/merging.

@sahilsharma011 in case of any doubt, lets have slack chat or Skype call on git branching for forking + git flow workflow.

2016-11-12 05:40 UTC, kapilsharma commented on composer.json
> +        "laravelcollective/html": "5.1.*"
These changes are not related to login form.

This probably happened due to wrong branch creation/merges.

2016-11-12 05:40 UTC, kapilsharma commented on database/seeds/August16ArticleSeeder.php
> -}
That is separate PR. Why it is showing as part of this PR?

These changes are not related to login form.

This probably happened due to wrong branch creation/merges.

2016-11-12 05:40 UTC, kapilsharma commented on database/seeds/DatabaseSeeder.php
> -        //$this->call(August16ArticleSeeder::class);
These changes are not related to login form.

This probably happened due to wrong branch creation/merges.

2016-11-12 05:40 UTC, kapilsharma commented on database/seeds/MagazineTableSeeder.php
> -}
These changes are not related to login form.

This probably happened due to wrong branch creation/merges.

2016-11-12 05:40 UTC, kapilsharma commented on resources/views/PhpReboot/Magazine/articleDetails.blade.php
> +@section('title', $article->title)
These changes are not related to login form.

This probably happened due to wrong branch creation/merges.

2016-11-12 05:40 UTC, kapilsharma commented on resources/views/PhpReboot/Magazine/monthPage.blade.php
> +@section('title', $magazine->name . 'magazine')
These changes are not related to login form.

This probably happened due to wrong branch creation/merges.

2016-11-12 05:40 UTC, kapilsharma commented on resources/views/auth/login.blade.php
> +                        @endif
Only these 9 lines should be part of new PR.

Can you please make new PR with only required code.

2016-11-12 05:41 UTC, closed without merging